CREATE TABLE [dbo].[MEDICAMENTO]
(
[IDMED] [int] NOT NULL IDENTITY(1, 1),
[NOMMED] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[STOMED] [int] NOT NULL,
[LABMED] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESMED] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NUMLOTMED] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREMED] [decimal] (5, 2) NOT NULL,
[FECVENMED] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDICAMENTO] ADD CONSTRAINT [MEDICAMENTO_pk] PRIMARY KEY CLUSTERED  ([IDMED]) ON [PRIMARY]
GO
