CREATE TABLE [dbo].[VENTA]
(
[IDVEN] [int] NOT NULL IDENTITY(1, 1),
[FECVEN] [date] NOT NULL,
[EMPLEADO_IDEMP] [int] NOT NULL,
[CLIENTE_IDCLI] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED  ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([CLIENTE_IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_EMPLEADO] FOREIGN KEY ([EMPLEADO_IDEMP]) REFERENCES [dbo].[EMPLEADO] ([IDEMP])
GO
