CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[CANMED] [int] NOT NULL,
[MEDICAMENTO_IDMED] [int] NOT NULL,
[VENTA_IDVEN] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_pk] PRIMARY KEY CLUSTERED  ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_MEDICAMENTO] FOREIGN KEY ([MEDICAMENTO_IDMED]) REFERENCES [dbo].[MEDICAMENTO] ([IDMED])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_VENTA] FOREIGN KEY ([VENTA_IDVEN]) REFERENCES [dbo].[VENTA] ([IDVEN])
GO
