CREATE TABLE [dbo].[CLIENTE]
(
[IDCLI] [int] NOT NULL IDENTITY(1, 1),
[NOMCLI] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APECLI] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNICLI] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_pk] PRIMARY KEY CLUSTERED  ([IDCLI]) ON [PRIMARY]
GO
