CREATE TABLE [dbo].[EMPLEADO]
(
[IDEMP] [int] NOT NULL IDENTITY(1, 1),
[NOMEMP] [varchar] (40) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APEEMP] [varchar] (70) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIEMP] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[USUEMP] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PASEMP] [varchar] (16) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEMP] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADO] ADD CONSTRAINT [EMPLEADO_pk] PRIMARY KEY CLUSTERED  ([IDEMP]) ON [PRIMARY]
GO
